// -------------------------------------------------------------
// 
// File Name: D:\fukuda\B4\HDLCoder\2023_12_15\PID_Attitude\PID_Attitude_Mixer_ver7_5\PID_Attitude_ver7_5\Mixer_block.v
// Created: 2024-02-07 16:17:48
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mixer_block
// Source Path: PID_Attitude_ver7_5/Mixer
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mixer_block
          (F_Throttle,
           F_Attitude,
           F_P);


  input   [11:0] F_Throttle;  // ufix12
  input   [31:0] F_Attitude;  // single
  output  [31:0] F_P;  // single


  wire [31:0] Data_Type_Conversion1_out1;  // ufix32
  wire [31:0] F_P_1;  // ufix32


  nfp_convert_fix_12_En0_to_single u_PID_Attitude_ver7_5_Mixer_nfp_convert_fix_12_En0_to_single (.nfp_in(F_Throttle),  // ufix12
                                                                                                 .nfp_out(Data_Type_Conversion1_out1)  // single
                                                                                                 );

  Mixer u_Mixer (.F_throttle(Data_Type_Conversion1_out1),  // single
                 .F_roll(F_Attitude),  // single
                 .F_P(F_P_1)  // single
                 );

  assign F_P = F_P_1;

endmodule  // Mixer_block

