// -------------------------------------------------------------
// 
// File Name: D:\fukuda\B4\HDLCoder\2023_12_15\PID_Attitude\PID_Attitude_Mixer_ver7_5\PID_Attitude_ver7_5\Mixer.v
// Created: 2024-02-07 16:17:48
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Mixer
// Source Path: PID_Attitude_ver7_5/Mixer/Mixer
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Mixer
          (F_throttle,
           F_roll,
           F_P);


  input   [31:0] F_throttle;  // single
  input   [31:0] F_roll;  // single
  output  [31:0] F_P;  // single


  wire [31:0] const_rsvd;  // ufix32
  wire [31:0] out0;  // ufix32
  wire pw2_sign_const;  // ufix1
  wire Out_1;
  wire signed [8:0] pw2_shift_const;  // sfix9
  wire [31:0] F_P_1;  // ufix32
  wire [31:0] F_P_2;  // ufix32


  assign const_rsvd = 32'h00000000;



  nfp_add_single u_nfp_add_comp (.nfp_in1(F_throttle),  // single
                                 .nfp_in2(F_roll),  // single
                                 .nfp_out(out0)  // single
                                 );

  assign pw2_sign_const = 1'b0;



  nfp_relop_single u_nfp_relop_comp (.nfp_in1(F_throttle),  // single
                                     .nfp_in2(const_rsvd),  // single
                                     .nfp_out1(Out_1)
                                     );

  assign pw2_shift_const = 9'sb111111110;



  nfp_gain_pow2_single u_nfp_gain_pow2_single (.nfp_in1(out0),  // single
                                               .nfp_in2(pw2_sign_const),  // ufix1
                                               .nfp_in3(pw2_shift_const),  // sfix9
                                               .nfp_out(F_P_1)  // single
                                               );

  assign F_P_2 = 32'h00000000;



  assign F_P = (Out_1 == 1'b0 ? F_P_1 :
              F_P_2);



endmodule  // Mixer

