// -------------------------------------------------------------
// 
// File Name: D:\fukuda\B4\HDLCoder\2023_12_15\PID_Attitude\PID_Attitude_Mixer_ver7_5\PID_Attitude_ver7_5\Motor_Controller.v
// Created: 2024-02-07 16:17:48
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Motor_Controller
// Source Path: PID_Attitude_ver7_5/Motor_Controller
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Motor_Controller
          (clk,
           reset_n,
           F_P,
           calib,
           rst,
           pwm);


  input   clk;
  input   reset_n;
  input   [31:0] F_P;  // single
  input   [10:0] calib;  // ufix11
  input   [10:0] rst;  // ufix11
  output  pwm;  // ufix1


  wire [31:0] Duty;  // ufix32
  wire [31:0] Data_Type_Conversion2_out1;  // uint32
  wire Motor_out1;  // ufix1


  Thrust_Duty u_Thrust_Duty (.F_P(F_P),  // single
                             .Duty(Duty)  // single
                             );

  nfp_convert_single_to_fix_32_En0 u_PID_Attitude_ver7_5_Motor_Controller_nfp_convert_single_to_fix_32_En0 (.nfp_in(Duty),  // single
                                                                                                            .nfp_out(Data_Type_Conversion2_out1)  // uint32
                                                                                                            );

  Motor u_Motor (.clk(clk),
                 .reset_n(reset_n),
                 .in(Data_Type_Conversion2_out1),  // uint32
                 .calib(calib),  // ufix11
                 .rst(rst),  // ufix11
                 .PWM(Motor_out1)  // ufix1
                 );

  assign pwm = Motor_out1;

endmodule  // Motor_Controller

