// -------------------------------------------------------------
// 
// File Name: D:\fukuda\B4\HDLCoder\2023_12_15\PID_Attitude\PID_Attitude_Mixer_ver7_5\PID_Attitude_ver7_5\PID_Attitude_ver7_5.v
// Created: 2024-02-07 16:17:48
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 5e+07
// Target subsystem base rate: 5e+07
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: PID_Attitude_ver7_5
// Source Path: PID_Attitude_ver7_5
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module PID_Attitude_ver7_5
          (clk,
           reset_n,
           r_throttle,
           x_gyro,
           imu_flag,
           calib,
           rst,
           pwm);


  input   clk;
  input   reset_n;
  input   [10:0] r_throttle;  // ufix11
  input   [15:0] x_gyro;  // uint16
  input   imu_flag;  // ufix1
  input   [10:0] calib;  // ufix11
  input   [10:0] rst;  // ufix11
  output  pwm;  // ufix1


  wire [11:0] F_Throttle;  // ufix12
  wire signed [15:0] Data_Type_Conversion_out1;  // int16
  wire [31:0] PID_Controller_Roll_out1;  // ufix32
  wire [31:0] F_P;  // ufix32
  wire Motor_Controller_out1;  // ufix1


  Throttle_Gain u_Throttle_Gain (.r_throttle(r_throttle),  // ufix11
                                 .F_Throttle(F_Throttle)  // ufix12
                                 );

  assign Data_Type_Conversion_out1 = x_gyro;



  PID_Controller_Roll u_PID_Controller_Roll (.clk(clk),
                                             .reset_n(reset_n),
                                             .x_gyro(Data_Type_Conversion_out1),  // int16
                                             .Trigger(imu_flag),  // ufix1
                                             .F_Roll(PID_Controller_Roll_out1)  // single
                                             );

  Mixer_block u_Mixer (.F_Throttle(F_Throttle),  // ufix12
                       .F_Attitude(PID_Controller_Roll_out1),  // single
                       .F_P(F_P)  // single
                       );

  Motor_Controller u_Motor_Controller (.clk(clk),
                                       .reset_n(reset_n),
                                       .F_P(F_P),  // single
                                       .calib(calib),  // ufix11
                                       .rst(rst),  // ufix11
                                       .pwm(Motor_Controller_out1)  // ufix1
                                       );

  assign pwm = Motor_Controller_out1;

endmodule  // PID_Attitude_ver7_5

