vlib work
vmap -c
vlog  nfp_gain_pow2_single.v
vlog  nfp_relop_single.v
vlog  nfp_add_single.v
vlog  Mixer.v
vlog  nfp_convert_fix_12_En0_to_single.v
vlog  Mixer_block.v
vlog  Duty.v
vlog  Motor.v
vlog  nfp_relop_single_block.v
vlog  nfp_relop_single_block1.v
vlog  nfp_mul_single.v
vlog  Thrust_Duty.v
vlog  nfp_convert_single_to_fix_32_En0.v
vlog  Motor_Controller.v
vlog  nfp_sub_single.v
vlog  nfp_convert_sfix_32_En20_to_single.v
vlog  PID_Controller_Roll.v
vlog  Throttle_Gain.v
vlog  PID_Attitude_ver7_5.v
