// -------------------------------------------------------------
// 
// File Name: D:\fukuda\B4\HDLCoder\2023_12_15\PID_Attitude\PID_Attitude_Mixer_ver7_5\PID_Attitude_ver7_5\Throttle_Gain.v
// Created: 2024-02-07 16:17:48
// 
// Generated by MATLAB 9.12 and HDL Coder 3.20
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Throttle_Gain
// Source Path: PID_Attitude_ver7_5/Throttle_Gain
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Throttle_Gain
          (r_throttle,
           F_Throttle);


  input   [10:0] r_throttle;  // ufix11
  output  [11:0] F_Throttle;  // ufix12


  wire [15:0] div_temp;  // ufix16
  wire [15:0] cast;  // ufix16_En5
  wire [10:0] sub_cast;  // ufix11
  wire [11:0] s;  // ufix12


  assign cast = {r_throttle, 5'b00000};
  assign div_temp = cast / 11'b11100000000;
  assign sub_cast = div_temp[10:0];
  assign s = {1'b0, sub_cast};
  assign F_Throttle = s - 12'b000000000110;



endmodule  // Throttle_Gain

